server:
  port: 10011

app:
  url: http://192.168.1.128:${server.port}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
