spring:
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    drop-first: false
    change-log: db/changelog/db.changelog-master.xml
